### ISSUE TITLE
Consider adding an end annotation parameter for MANE Transcript

### ISSUE THREAD

**Issue by korikuzma** [cancervariants/variation-normalization#166]
We currently do the following in normalize:
```
p -> p
c -> c
g (no gene) -> GRCh38
g (with gene) -> c 
```

However some users may want to go from `p -> g` instead of the default (`p -> p`)

**Comment by korikuzma** [comment]
Or if we didn't want to provide an extra parameter, we could add the other coordinates in `extensions`. Example: Given a `p` coordinate, return Variation Descriptor with `p` coordinate and in `extensions` add variations for `c` and `g` coordinates. @MayLiu27 Do you all have a preference? I sort of like adding it to extensions.

**Comment by MayLiu27** [comment]
> Or if we didn't want to provide an extra parameter, we could add the other coordinates in `extensions`. Example: Given a `p` coordinate, return Variation Descriptor with `p` coordinate and in `extensions` add variations for `c` and `g` coordinates. @MayLiu27 Do you all have a preference? I sort of like adding it to extensions.

Yeah leave them in extension would be good enough as long as we have them.

**Comment by MayLiu27** [comment]
Discussed with @liux8 , the process will be difficult to achieve as the codon-to-amino acid mapping is a many-to-one mapping. So it's possible we got many results for just one variant and that's something we try to avoid.
The current process could address our needs. You can close this issue for now.  
Thanks Kori.
