### ISSUE TITLE
Default "label" to query expression in normalize API

### ISSUE THREAD

**Issue by larrybabb** [cancervariants/variation-normalization#240]
I would like to discuss the idea of defaulting the `label` attribute of the `VariationDescriptor` produced by the normalize api to be the query value used to make the request. I think it will likely be that folks will want to use the hgvs expression as the label of the normalized variation produced. I think this may also be true for when folks use a gnomad, iscn or spdi type string as well.

**Comment by korikuzma** [comment]
That makes sense to me!

**Comment by larrybabb** [comment]
@ahwagner unless you have any concerns then let's just do this for now, seems simple and will help a little

**Comment by ahwagner** [comment]
Sounds good, no concerns.
