### ISSUE TITLE
Support ClinVar Copy Number Gain/Loss

### ISSUE THREAD

**Issue by korikuzma** [cancervariants/variation-normalization#285]
@larrybabb :

> I like @theferrit32 ’s idea of setting up the endpoint to allow us to send the parsed components `assembly`, `chr`,` start range/number`, `end range/number`, `total copies`.  It would also be nice to have the option to send either `assembly + chr` vs `sequence accession` since both of these practices are quite common.  The assembly choices should be enumerated to `GRCh38`, `GRCh37`, `NCBI36`, `hg20`, `hg19`, `hg18`. IMO.

[Examples of ClinVar Copy Number Gain/Loss](https://www.ncbi.nlm.nih.gov/clinvar?term=((%22copy%20number%20gain%22%5BType%20of%20variation%5D%20OR%20%22copy%20number%20loss%22%5BType%20of%20variation%5D )

**Comment by larrybabb** [comment]
@korikuzma ClinVar only uses GRCH38, GRCH37 and NCBI36.  I added hg20, hg19, and hg18 because I've seen folks use this to correspond to them, respectively. As long as the first 3 are available that is all that we would need for now.

**Comment by larrybabb** [comment]
I haven't seen `hg38` before but that could be my lack of experience.
