### ISSUE TITLE
Token match_type / token_type params

### ISSUE THREAD

**Issue by ahwagner** [cancervariants/variation-normalization#3]
Right now our classifier runs on a simple rule-based classification heuristic.

We should consider expanding this to incorporate tokens with associated weights.

Consider, for example, the notion of `BCR-ABL fusions`. Assuming that we resolve #2 and add alias support, ABL would naïvely resolve to a few possibilities:
1) Previous gene symbol for ABL1
2) Known alias for MTTP gene

In the case of this specific gene pair, it is certain that 1) is intended. To address this, I propose we add weights to tokens (broadly). 

For gene tokens, matches to primary identifiers (e.g. ABL1) would always have weight=1. For indirect matches through aliases / previous symbols, these weights should be 1/n, where n=primary records linked to the search term through these matches. 

These weights should be used downstream by the classifiers, and we should allow classifiers to reweight tokens based on observed patterns (i.e. BCR-ABL genepair token + fusion token -> BCR-ABL1 Fusions, high confidence).

**Comment by ahwagner** [comment]
While weighting might be useful for fuzzy search later, for now we can capture the match characteristics as token params, and turn those into confidences in classification.

We discussed the `match_type` parameter for gene tokens specifically, describing if a gene match was to (for example) a primary, previous, or alias symbol. We might also consider a `source` parameter describing the identifier source (e.g. HGNC symbol, numeric ID, Ensembl ID, Entrez ID).

**Comment by korikuzma** [comment]
We already have this
