### ISSUE TITLE
Expand support for categorical variation wrt VAI needs

### ISSUE THREAD

**Issue by wesleygoar** [cancervariants/variation-normalization#327]

**Comment by korikuzma** [comment]
@wesleygoar should this be in the vai repo? We'll probably need to make related issues for being able to represent categorical variation which will help with the above goal

**Comment by wesleygoar** [comment]
Hmm good question. @ahwagner what are your thoughts?

**Comment by korikuzma** [comment]
@wesleygoar Or just rename the epic to expand support for categorical variation wrt VAI needs

**Comment by wesleygoar** [comment]
First stage of this has been completed allowing for gene search.

**Comment by korikuzma** [comment]
Closing. There are no variation-normalizer issues associated to this epic and I don't think it belongs in this repo.
