### ISSUE TITLE
Identify amount of evidence associated to variant categories

### ISSUE THREAD

**Issue by anastasiasmith1221** [cancervariants/variation-normalization#405]
The variant categories found in #287

**Comment by korikuzma** [comment]
> @wesleygoar Identify the amount of evidence attached to each of the categories we created in civic. So then we can see the percent of evidence attached to specific variant categories.

> @korikuzma Do you care about the scores or no?
> @wesleygoar Ah yes this is very interesting data

> @korikuzma Additionally, are we only concerned about accepted evidence?
> @wesleygoar I would like that data captured for potential data slicing

**Comment by korikuzma** [comment]
@anastasiasmith1221 can you push your changes + create a PR into mine so we can review?

**Comment by korikuzma** [comment]
@anastasiasmith1221 if it's not ready to be merged, you can create a draft PR

**Comment by anastasiasmith1221** [comment]
This is for CIViC and MOAlmanac
