### ISSUE TITLE
Make our HGVS syntax checker be more generalized / non-type specific

### ISSUE THREAD

**Issue by korikuzma** [cancervariants/variation-normalization#56]
Currently `NP_000542.1:p.Tyr185Ter` matches as a HGVS token but `np_000542.1:p.tyr185ter` does not. Both queries should be HGVS tokens.

**Comment by ahwagner** [comment]
We should make our HGVS syntax checker be more generalized / non-type specific. Does the `hgvs` package have a regex or validate command we can leverage for that?

**Comment by korikuzma** [comment]
@ahwagner If more generalized / non-type specific means accepting the various molecule contexts (genomic, transcript, or protein), then yes. The `hgvs` package does have `parse_hgvs_variant` which we currently use during tokenization. 

```
>>> from hgvs.parser import Parser
>>> parser = Parser()
>>> parser.parse_hgvs_variant("NC_000023.10:g.33038255C>A")
SequenceVariant(ac=NC_000023.10, type=g, posedit=33038255C>A, gene=None)
>>> parser.parse_hgvs_variant("NM_004006.2:c.4375C>T")
SequenceVariant(ac=NM_004006.2, type=c, posedit=4375C>T, gene=None)
>>> parser.parse_hgvs_variant("NP_003997.1:p.Arg1459*")
SequenceVariant(ac=NP_003997.1, type=p, posedit=Arg1459Ter, gene=None)
```

**Comment by korikuzma** [comment]
The tool is case sensitive. This issue is stale and not sure what was meant by making syntax checker be more generalized, so closing.
